export const sacCodes = [
  {
    id: 1,
    code: "01",
    description: "Books",
    gstRate: 5,
  },
  {
    id: 2,
    code: "02",
    description: "Newspapers, magazines, journals and periodicals",
    gstRate: 5,
  },
  {
    id: 3,
    code: "03",
    description: "Advertising",
    gstRate: 18,
  },
  {
    id: 4,
    code: "04",
    description: "Legal services",
    gstRate: 18,
  },
  {
    id: 5,
    code: "05",
    description: "Education and training services",
    gstRate: 5,
  },
  {
    id: 6,
    code: "06",
    description: "Health care services",
    gstRate: 5,
  },
  {
    id: 7,
    code: "07",
    description: "Sports and recreational services",
    gstRate: 18,
  },
  {
    id: 8,
    code: "08",
    description: "Financial services",
    gstRate: 18,
  },
  {
    id: 9,
    code: "09",
    description: "Transport services",
    gstRate: 5,
  },
  {
    id: 10,
    code: "10",
    description: "Accommodation services",
    gstRate: 5,
  },
  {
    id: 11,
    code: "11",
    description: "Food and beverages",
    gstRate: 18,
  },
  {
    id: 12,
    code: "12",
    description: "Durable goods",
    gstRate: 28,
  },
  {
    id: 13,
    code: "13",
    description: "Non-durable goods",
    gstRate: 18,
  },
  {
    id: 14,
    code: "14",
    description: "Services relating to supply of goods",
    gstRate: 18,
  },
  {
    id: 15,
    code: "15",
    description: "Works contract services",
    gstRate: 18,
  },
  {
    id: 16,
    code: "16",
    description: "Miscellaneous services",
    gstRate: 18,
  },
];
